//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroFacebookAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsView
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorLastName { get; set; }
        public string Content { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public string TargetUserFirstName { get; set; }
        public string TargetUserLastName { get; set; }
        public System.DateTime PostDate { get; set; }
        public string PrimaryPostAuthorFirstName { get; set; }
        public string PrimaryPostAuthorLastName { get; set; }
        public Nullable<System.DateTime> PrimaryPostDate { get; set; }
    }
}
